version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "practicum"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5999:5432"
    volumes:
      - ./sql/user_table.sql:/docker-entrypoint-initdb.d/user_table.sql