version: "3.9"
services:
  postgres:
      image: postgres
      environment:
        POSTGRES_DB: "practicum"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      ports:
        - "5999:5432"
      volumes:
        - ./sql/create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
